"""Added new commission fields

Revision ID: 3bfd7087fa04
Revises: 9c4c22df775f
Create Date: 2025-03-10 11:30:34.399429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfd7087fa04'
down_revision = '9c4c22df775f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashin_total_transactions', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashin_total_value', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashin_total_tax_on_valid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashin_payout_commission', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_total_transactions', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_total_value', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_total_tax_on_valid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_payout_commission', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_commissions_due', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.drop_column('total_commissions_due')
        batch_op.drop_column('cashout_payout_commission')
        batch_op.drop_column('cashout_total_tax_on_valid')
        batch_op.drop_column('cashout_total_value')
        batch_op.drop_column('cashout_total_transactions')
        batch_op.drop_column('cashin_payout_commission')
        batch_op.drop_column('cashin_total_tax_on_valid')
        batch_op.drop_column('cashin_total_value')
        batch_op.drop_column('cashin_total_transactions')

    # ### end Alembic commands ###
