"""Add reset token fields

Revision ID: 5f3500dbf399
Revises: 11b63187e6ac
Create Date: 2025-03-14 08:09:12.006287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3500dbf399'
down_revision = '11b63187e6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=6), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
