"""Initial migration

Revision ID: 8cd23118a899
Revises: 
Create Date: 2025-03-07 09:46:25.599714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd23118a899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('pdfs_assigned_to_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_table', ['assigned_to'], ['id'])

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_constraint('user_table_phone_number_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_table_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_table_phone_number'))
        batch_op.create_unique_constraint('user_table_phone_number_key', ['phone_number'])
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pdfs_assigned_to_fkey', 'user_table', ['assigned_to'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('filepath',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
