"""Add missing commission fields

Revision ID: e1f32158563d
Revises: 3bfd7087fa04
Create Date: 2025-03-10 22:29:47.683851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f32158563d'
down_revision = '3bfd7087fa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashin_total_number_valid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashin_total_value_valid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_total_number_valid', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cashout_total_value_valid', sa.String(length=20), nullable=True))
        batch_op.drop_column('cashout_total_numbervalid')
        batch_op.drop_column('cashout_total_valuevalid')
        batch_op.drop_column('cashin_total_valuevalid')
        batch_op.drop_column('cashin_total_numbervalid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashin_total_numbervalid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cashin_total_valuevalid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cashout_total_valuevalid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cashout_total_numbervalid', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('cashout_total_value_valid')
        batch_op.drop_column('cashout_total_number_valid')
        batch_op.drop_column('cashin_total_value_valid')
        batch_op.drop_column('cashin_total_number_valid')

    # ### end Alembic commands ###
